### ISSUE TITLE
CRUD de Estudiante

### ISSUE THREAD

**Issue by neftalyluis** [neftalyluis/course-manager#3]
Amigo @Merak1 del internet, estos son los nuevos pendientes, los iré actualizando conforme los recuerde:

- [x] Agregar Botón y Modal para asignar Curso en la vista de checkStudent
- [x] Crear acción en Controlador (Yo lo hago)
- [x] Crear Tabla de Boostrap para mostrar los cursos asignados, con botón de eliminar estudiante de curso en checkStudent
- [x] Crear vista de crear estudiante en un modal en la pagina de index
- [x] Crear vista de actualizacion de estudiante en un modal en la pagina de checkStudent
- [ ] Agregar vistas para el flash

**Comment by neftalyluis** [comment]
Cualquier duda, podemos checarlo

**Comment by Merak1** [comment]
Crear vista de actualizacion de estudiante en un modal en la pagina de checkStudent

Cuarto punto queda pendiente por que el abi no se acuerda que quiere decir.

**Comment by neftalyluis** [comment]
Cierro
