### ISSUE TITLE
CRUD de Curso

### ISSUE THREAD

**Issue by neftalyluis** [neftalyluis/course-manager#4]
Amigo @Merak1 del internet, estos son los pendientes para CourseManager, los iré actualizando conforme los recuerde:

- [ ] Agregar Botón y Modal para asignar Leccion en la vista de checkCourse
- [ ] Crear acción en Controlador (Yo lo hago)
- [ ] Crear Tabla de Boostrap para mostrar las lecciones, con botón de eliminar leccion de curso en checkStudent
- [ ] Crear vista de crear Curso en un modal en la pagina de index
- [ ] Crear vista de actualizacion de Curso en un modal en la pagina de checkCourse
- [ ] Agregar vistas para el flash

**Comment by Merak1** [comment]
![screenshot_4](https://user-images.githubusercontent.com/19805451/31461174-51633ed2-ae8e-11e7-871c-342faf23f3f1.png)


Se agrega modal con los inputs y textareas de el crear nuevo curso y en el botón de cerrar de este nodal de creación de curso aparece un nodal de confirmación

![screenshot_1](https://user-images.githubusercontent.com/19805451/31461235-89bdf736-ae8e-11e7-800c-4d5aa9809425.png)


En espera para ver si le hago PR

**Comment by neftalyluis** [comment]
Hazme el PR uwu

**Comment by Merak1** [comment]
La persona robusta va solamente con ese cambio, ando haciendo todo lo demás aparte y ahorita te aviso cuando tenga lo demás.
