### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by neftalyluis** [neftalyluis/course-manager#9]
@Merak1, necesitas agregar este snippet después de la etiqueta `</head>` en el archivo con ruta `grails-app/views/layouts/main.gsp`

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-110000480-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-110000480-1');
</script>
```

Cuando levantes la aplicación en teoría no debería de salir ningún error en la consola de JS

Cualquier cosa mandame mensaje

**Comment by Merak1** [comment]
Se agrega un snippet en el main layout y se revisa que no mande error
